// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcBOeee6qDUztnh7OCDbqqeO1gc08Omhw',
    appId: '1:496964501572:web:b6b609dd82aed0c7593c11',
    messagingSenderId: '496964501572',
    projectId: 'chatapp-3ffc4',
    authDomain: 'chatapp-3ffc4.firebaseapp.com',
    databaseURL: 'https://chatapp-3ffc4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chatapp-3ffc4.firebasestorage.app',
    measurementId: 'G-YQYLQDFZZ6',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM6orLdM3yUsfb_99cZvA9IzvG3mBYu4k',
    appId: '1:157669961962:ios:a6850ef6c047a41feaa793',
    messagingSenderId: '157669961962',
    projectId: 'cnpm-bb625',
    storageBucket: 'cnpm-bb625.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDM6orLdM3yUsfb_99cZvA9IzvG3mBYu4k',
    appId: '1:157669961962:ios:a6850ef6c047a41feaa793',
    messagingSenderId: '157669961962',
    projectId: 'cnpm-bb625',
    storageBucket: 'cnpm-bb625.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZ2kwgqKRV6ZpoVh3nDt4jFvbZcCMcgAU',
    appId: '1:157669961962:web:229da573d2a54667eaa793',
    messagingSenderId: '157669961962',
    projectId: 'cnpm-bb625',
    authDomain: 'cnpm-bb625.firebaseapp.com',
    storageBucket: 'cnpm-bb625.firebasestorage.app',
    measurementId: 'G-D8G29SDBDP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSsmsXXdeq41DPTkn5dDML6ygAKRnYygo',
    appId: '1:496964501572:android:94b0cd4f143a45af593c11',
    messagingSenderId: '496964501572',
    projectId: 'chatapp-3ffc4',
    databaseURL: 'https://chatapp-3ffc4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chatapp-3ffc4.firebasestorage.app',
  );

}